In [47]:
from plant_processing import Source 
import pandas as pd 
import matplotlib.pyplot as plt 
import numpy as np 
import requests 
from datetime import date

In [48]:
api_key = "YOUR API KEY"
latitude = 13.082680
longitude = 80.270721
date = date.today()
interval  = "15m"  #15 minute intervals

url_sunhours = "https://api.openweathermap.org/energy/1.0/solar/interval_data?lat={}&lon={}&date={}&interval={}&tz=+05:30&appid={}".format(latitude,longitude,date,interval,api_key)

print(url_sunhours)

https://api.openweathermap.org/energy/1.0/solar/interval_data?lat=13.08268&lon=80.270721&date=2024-05-11&interval=15m&tz=+05:30&appid=yourapi


Importing the dataset that has been processed

In [49]:
dataset = pd.read_csv("/Users/aditirajesh/Desktop/program_files/python/python_6sem/DATA_PLANTS/plant1/data15_1.csv")
x = dataset.iloc[:,1:4].values
y = dataset.iloc[:,-1].values

print(dataset)

          DATE  AMBIENT_TEMP  MODULE_TEMP  SUN_HOURS        YIELD
0   2020-05-15     30.101998    40.874126   4.758980  6176.000000
1   2020-05-16     28.693978    38.971222   4.662886  6450.000000
2   2020-05-17     29.629909    42.436575   5.732761  7391.000000
3   2020-05-18     25.220109    33.840217   3.816491  5286.000000
4   2020-05-19     27.493836    38.077856   4.511132  6790.000000
5   2020-05-20     27.210057    40.353065   4.561357  8663.750000
6   2020-05-21     29.383561    45.335427   5.889043  7598.571429
7   2020-05-22     28.612870    41.123396   5.529507  7000.000000
8   2020-05-23     29.387591    45.663036   6.526639  8394.857143
9   2020-05-24     29.915382    43.727070   6.233824  7554.750000
10  2020-05-25     29.942647    45.106869   6.807852  8085.000000
11  2020-05-26     29.596173    43.869744   6.062268  7712.000000
12  2020-05-27     29.593112    41.672768   5.134159  6564.000000
13  2020-05-28     29.773013    43.832226   6.507684  8314.750000
14  2020-0

Taking care of missing data

In [50]:
from sklearn.impute import SimpleImputer 
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')   #replacing all the missing values in the dataset with the mean.
imputer.fit(x[:,:]) #connects the imputer to the matriX of features 
x[:,:] = imputer.transform(x[:,:])

splitting into training and test set

In [51]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state=1)

In [52]:
print(x_train)

[[28.04 41.24  6.19]
 [27.51 40.88  6.33]
 [25.57 36.26  5.28]
 [26.64 36.41  4.41]
 [26.22 36.67  4.88]
 [27.49 38.08  4.51]
 [29.63 42.44  5.73]
 [26.72 39.71  5.8 ]
 [26.86 40.54  6.1 ]
 [29.94 45.11  6.81]
 [26.5  39.44  6.35]
 [25.52 33.59  4.08]
 [25.98 37.3   5.37]
 [29.38 45.34  5.89]
 [29.77 43.83  6.51]
 [28.61 41.12  5.53]
 [25.59 34.39  4.25]
 [28.69 38.97  4.66]
 [27.07 37.55  4.41]
 [30.1  40.87  4.76]
 [26.88 39.17  5.47]
 [27.21 40.35  4.56]
 [29.6  43.87  6.06]
 [29.92 43.73  6.23]
 [26.66 37.22  4.94]
 [29.39 45.66  6.53]
 [29.59 41.67  5.13]]


In [53]:
print(y_train)

[7844.88 8216.29 7164.75 5751.   6197.   6790.   7391.   7456.5  8019.
 8085.   8254.43 5709.38 7326.33 7598.57 8314.75 7000.   5757.43 6450.
 5965.   6176.   7146.   8663.75 7712.   7554.75 6563.71 8394.86 6564.  ]


In [54]:
print(x_test)

[[28.06 44.42  6.2 ]
 [26.38 37.92  5.48]
 [25.22 33.84  3.82]
 [25.84 33.65  3.88]
 [26.56 36.59  4.49]
 [26.67 36.5   4.81]
 [27.26 40.54  6.17]]


In [55]:
print(y_test)

[7951.   7698.62 5286.   5520.25 6123.71 6277.   8009.  ]


In [56]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
model = regressor.fit(x_train, y_train)

In [57]:
model.score(x_test,y_test)

0.8187919258462268

In [58]:
model.score(x_train,y_train)

0.8014869322092024

In [59]:
from sklearn import linear_model
lasso_reg = linear_model.Lasso(alpha=50,max_iter=100,tol=0.1)
lasso_reg.fit(x_train,y_train)

Lasso(alpha=50, max_iter=100, tol=0.1)

In [60]:
lasso_reg.score(x_test,y_test)


0.8655873688398775

In [61]:
lasso_reg.score(x_train,y_train)

0.7591844707796963

In [62]:
coefficients = model.coef_
intercept = model.intercept_



In [63]:
y2_pred = lasso_reg.predict(x_test)
print(np.concatenate((y2_pred.reshape(len(y2_pred),1), y_test.reshape(len(y_test),1)),1))

[[8351.84 7951.  ]
 [7116.15 7698.62]
 [5885.58 5286.  ]
 [5717.69 5520.25]
 [6400.47 6123.71]
 [6476.3  6277.  ]
 [7718.39 8009.  ]]


In [64]:
y_pred = regressor.predict(x_test)
y_pred_train = regressor.predict(x_train)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[8833.   7951.  ]
 [7199.91 7698.62]
 [5895.12 5286.  ]
 [5519.2  5520.25]
 [6358.83 6123.71]
 [6351.79 6277.  ]
 [7856.22 8009.  ]]


In [65]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)
print(rmse)

460.10624527332254


In [66]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_train,y_pred_train)
rmse = np.sqrt(mse)
print(rmse)

393.4495793164891


In [67]:
response = requests.get(url_sunhours)
data = response.json()
irradiation_today = data['irradiance']['daily']
print(irradiation_today)
cloudy_sky_irr = irradiation_today[0]['cloudy_sky']['dni']
print(cloudy_sky_irr)

[{'clear_sky': {'ghi': 7979.24, 'dni': 9613.4, 'dhi': 1221.0}, 'cloudy_sky': {'ghi': 4051.7, 'dni': 1830.66, 'dhi': 2953.04}}]
1830.66
